spring:
    datasource:
      url: jdbc:h2:file:./data/snippetdb
      driver-class-name: org.h2.Driver
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
server:
    port: 8081
